pinterest/arcanist-linters

README.md, __phutil_library_map__.php, src/ArcanistEslintLinter.php, src/ESLintLinter.php
Adds a linter to check for errors in JavaScript and JSX files.
The binary to use is set as a configuration option, so it can be project specific. The default is to try and use `eslint` that's on your $PATH.
=> Add an eslint linter

src/PrettierESLintLinter.php, src/PrettierLinter.php, src/PythonIsortLinter.php
Arcanist applies some basic filtering to `arc lint` so that only lint
messages on or near changed lines are raised to the user.
This is generally helpful because it avoids drawing attention to parts
of the file that are unrelated to the change, but, in the case of these
"beautifying" linters, it means that some changes might not be included
in the final auto-fixed file diff.
Fortunately, we can bypass this filtering on a per-message basis.
=> Bypass "changed line" filtering in beautifiers

src/CheckstyleLinter.php
When trying out the Checkstyle linter, I noticed that we sometimes weren't parsing out the correct line and character values. This then would cause the `ArcanistLintMessage` to point to the wrong spot in the code.
For example, using the following example output:
`[WARN] /some/path/to/file.java:49:8: Unused import - com.some.package.Class. [UnusedImports]`
The existing regex would incorrectly believe `path` was `/some/path/to/file.java:49` and the line number was `8`. With the proposed pull request of making the regex lazy for the `path` grouping, we will then correctly have `path` be `/some/path/to/file.java`, line number be `49`, and character be `8`.
The canonical output of `[WARN] /some/path.java:123: Some message [etc]` is still parsed correctly.
=> Update Checkstyle regex to correctly parse line & char values from output

src/PythonRequirementsLinter.php
Environment markers can be added at the end of a package requirement
line following a semicolon. For example:
Django==1.5.4; python_version < '3'
Teach the parser to recognize this part of the requirements grammar and
use it to allow duplicate package names that have different
requirements. For example, this is now valid:
Django==1.5.4; python_version < '3'
Django==1.11.18; python_version >= '3'
Also, adjust the "unsorted" rule to allow duplicate package names but
enforce the sort order of their version strings.
=> Support package environment markers

src/PythonIsortLinter.php
In isort 4.3.11, the default "skip" behavior changed. Filenames passed
on the command line were no longer subject to "skip" rules from the
configuration file.
isort 4.3.18 provides the `--filter-files` command line option that
restores that behavior. Pass it when we're running at least that version
so that our linter respects the configuration settings.
=> Pass --filter-files to newer isort versions

src/ESLintLinter.php
Parsing errors come out with null names, which crashes arc. Give null names a name.
=> Set a default name for rules with null names

src/ESLintLinter.php
First of all, thanks for publishing your linters!
I've been into an issue with the `eslint` linter: My `.arclint` enables the linter for `"include": ["(\\.(j|t)sx?$)"],` while excludes are defined in `.eslintignore` (so that other tools also respect them).
Some version of ESLint (IIRC last year) started emitting a warning so that if one invokes `eslint some-ignored-file.js`, it communicates to the user that it ignored it.
The warning doesn't have most fields set, so PHP emits a bunch of warnings when building `ArcanistLintMessage`. This change makes the linter just ignore that warning.
=> Skip file ignored warning

src/ESLintLinter.php
I found eslint sometimes has a message "File ignored by default", which causes errors.
I think it would be more robust if you just check for the presence of the `ruleId` field which seems to be missing for the ignored files, but I don't know PHP so I'll leave that to you.
=> Ignore "File ignored by default" messages in eslint

README.md, src/BlackLinter.php
• Change `--quiet` to `--check`, this will result in messages that the linter failed rather than quietly making changes, which may compete with other linters like isort
• Add `--skip-string-normalization` option
• More verbose error message for when `--check` fails:
```
Error  () BLACK
Please run `black -S <FILEPATH>`
```
for when black.stringnormalizaton = false
and
```
Error  () BLACK
Please run `black <FILEPATH>`
```
for when black.stringnormalizaton = true
=> Black linter message

src/BlackLinter.php
We were already removing --check; we now also remove --quiet.
Also use array_diff() as a simpler way of pruning these items from the
$flags array.
=> Remove --check and --quiet from suggested command line

src/BlackLinter.php
This linter is currently written to only check the format of Python
files but not to also autoformat them (which would conflict with the
isort linter; more work here is needed). Given that, we should always
pass these flags to black.
Also, check for the 0 error code, which indicates that black didn't find
any formatting issues in the linted file.
=> Always pass --quiet and --check to black

src/ESLintLinter.php
The code isn't supposed to be the violating source code, but some "identifier" for the violation.  Some [examples](https://github.com/phacility/arcanist/blob/222800a86ed002c564e2760d6c5d9e93810b5b96/src/lint/linter/ArcanistTextLinter.php#L8-L16) are:
```
final class ArcanistTextLinter extends ArcanistLinter {
const LINT_DOS_NEWLINE          = 1;
const LINT_TAB_LITERAL          = 2;
const LINT_LINE_WRAP            = 3;
const LINT_EOF_NEWLINE          = 4;
const LINT_BAD_CHARSET          = 5;
const LINT_TRAILING_WHITESPACE  = 6;
const LINT_BOF_WHITESPACE       = 8;
const LINT_EOF_WHITESPACE       = 9;
const LINT_EMPTY_FILE           = 10;
```
A common pattern seems to be to just pass `$this->getLinterName()` there's just no real code. Also done in the `PrettierLinter` in this repo.
=> ESLintLinter: Pass name as code

src/BlackLinter.php
This field is a required part of a complete ArcanistLintMessage.
=> Also set the 'code' field in Black lint messages

src/PythonIsortLinter.php
This means it will run earlier in the linting sequence, which is helpful
because it deals with style and emits autofix patch output.
=> Lower the priority of the isort linter

src/PythonRequirementsLinter.php
This was an oversight that now results in PCRE compilation errors
("invalid range in character class").
=> Escape hyphens in regex character classes

src/PythonExternalLinter.php
If the shell environment has an activated virtualenv, defer to PATH. We
could also extract this directory from the environment variable and add
it to the front of our our search list below, but that might be more
confusing than helpful in practice.
=> Skip virtualenv search when VIRTUAL_ENV is active

src/ESLintLinter.php
It caused an error while sending a diff:
```
ERR-CONDUIT-CORE: Parameter 'name' has invalid type. Expected type 'string', got type 'bool'. at [<arcanist>/src/conduit/ConduitFuture.php:66]
```
It was cause by this line of code:
```
$message->setName($offense['ruleId'] || 'unknown');
```
that set the rule name to `true` instead of the ruleID
=> Fix ruleID being set to 'true' 

src/BlackLinter.php
Read the version string from STDOUT (not STDERR). Also, there's no need
to persist the parsed version string as an instance variable.
=> Fix black version parsing

src/PythonIsortLinter.php
https://github.com/PyCQA/isort/issues/1429 fixed `--check`'s output so
that the error message and diff output are separated into STDERR and
STDOUT rather than combined in STDOUT. This means we need to update our
diff parsing function accordingly.
Also fix the version parsing routine to read from STDOUT. This was
busted for at least a few versions.
=> Update diff parsing for isort 5.5+

src/NodeExternalLinter.php
If we didn't get a `$path` from `yarn`, it won't be set. Check for its existence to avoid
```Undefined variable: path```
This fixes the changes from a7cbfa1dc9b2daee679b2a9b05cd23dbdee81a6a
=> [BUGFIX] Fix undefined path variable

src/NodeExternalLinter.php, src/OpenApiLinter.php
Not all npm packages use the same name for their main binary as the name of the package in the npm repository.
This change separates these configs so they can be different, but assumes they are the same as default behavior.
The result is that the OpenAPI linter now provides correct install instructions when it is missing:
```
Some linters failed:
    - ArcanistMissingLinterException: Unable to locate binary "lint-openapi" to run linter OpenApiLinter. You may need to install the binary, or adjust your linter configuration.
      TO INSTALL:
      [lint-openapi globally] run: `npm install --global ibm-openapi-validator`
      [lint-openapi locally] run either: `npm install --save-dev ibm-openapi-validator` OR `yarn add --dev ibm-openapi-validator`
```
=> Specify a different npm package name from node binary

src/BlackLinter.php, src/DetectSecretsLinter.php, src/Flake8Linter.php, src/NodeExternalLinter.php, src/PinterestPylintLinter.php, src/PythonExternalLinter.php, src/PythonIsortLinter.php
In some cases, a repository using Arcanist linters may have a particular way of installing lint dependencies — a `requirements.txt` or `package.json` file, say.
Here we add an `install-instructions` config option to all linters built on `PythonExternalLinter` or `NodeExternalLinter`. If specified, the text printed when the required binary cannot be found will be that specified in the configuration rather than the default text.
Child linters are modified to follow the convention set in the base classes so that they inherit this behavior. The `Flake8Linter` already had a mechanism for specifying custom instructions; this behavior is preserved for backwards compatibility.
For example, with `"install-instructions": "make lint_requirements"`, the message looks like:
```
Some linters failed: …
```
=> Add `install-instructions` option to Node and Python linters

src/NodeExternalLinter.php
XHPAST can't handle a final trailing comma in the argument list.
=> Fix a XHPAST parse error

src/ESLintLinter.php
There is an edge case while running ESlint that can cause Arcanist to crash with the following error message:
> Linter "ESLintLinter" generated a lint message that is invalid because it does not have a name. Lint messages must have a name.
This edge case can be triggered by trying to lint a source file with a syntax error in it. That produces an ESlint JSON output where ruleId is null.
The idx function however does not fall back to using the provided default value 'unknown'.
It does actually the following: if the dictionary property value is null, and if the tested key (here ruleId) exists in the dictionary, then it returns null instead of the fallback default value.
This fix makes sure we never set a null value for the name property.
- Ran `arc lint` in a local project with a modified JS …
=> Fixed an Arcanist crash bug caused by ruleId being null

README.md, src/OpenApiLinter.php
- Tweak the reported names to match the existing conventions
- Use `--version` to query the version string (and `trim()` it)
- Request `--verbose` JSON output to also report the rule names
- Use the rule name as the linter message's "code"
- Document that we now support v0.34.1 and later
=> Revise the OpenAPI validator / linter

src/ESLintLinter.php
We've encountered a number of cases where the eslint result doesn't
include values for all of these expected keys. Harden the code for these
cases using idx(). The internal Arcanist interface allows these values
to be `null`, which is idx()'s default value.
Fixes #62
=> Handle missing "offense" values

README.md, src/OpenApiLinter.php
The OpenAPI linter prints error information both [to `stderr`](https://github.com/IBM/openapi-validator/blob/7292b7b312d92f41bcfa970b87f067f3f593b4d2/src/plugins/ast/ast.js#L180) and [to `stdout`](https://github.com/IBM/openapi-validator/blob/927530a97fb4f062f4d5cab8745581959cc12ebc/src/cli-validator/utils/printError.js#L2). Previously we were only showing the contents of `stderr` when an error occurred, meaning that errors could be thrown with no discernable message or cause.
This also allows use of the `--debug` option to add in stacktraces.
=> Show stdout in OpenAPI Linter exceptions

src/PythonRequirementsLinter.php
This regular expression previously only supported a single 'extra', but
multiple 'extras' can be specified when separated by commas.
=> Support multiple comma-separated 'extras'

src/PyrightLinter.php
Both the line and character offsets are 0-indexed in the json format, whereas the human-visible version is 1-indexed
=> Treat Pyright json output as 0-indexed

src/ApacheThriftLinter.php
Use the `thrift.install` configuration key to provide a string that will
be used instead of the default installation string. This is useful for
site-local installation instructions.
=> Support custom Thrift installation instructions

README.md, src/OpenApiLinter.php
- Output process functions is updated to support version v0.36 and later
- Updated Sample Output according to versions greater than v0.36
=> Update OpenAPI Linter for supporting v0.36 and later

src/PyrightLinter.php
The JSON output format for Pyright [changed in version 1.1.126](https://github.com/microsoft/pyright/pull/1749).
This makes it so we can handle both the new and previous output formats.
=> Handle new Pyright output format

README.md, src/SpectralLinter.php
This is a friendlier way to pass set --ruleset flag.
Also, map the 'info' and 'hint' severities to "ADVICE" and allow user
customization of these mappings.
=> Provide a configuration key for Spectral ruleset

src/ESLintLinter.php, src/NodeExternalLinter.php
Directory structure:
```
/Users/mmark/code/my-repo
|-- .arclint
|-- client
|-- node_modules
|-- .eslintrc
|-- server
|-- node_modules
|-- .eslintrc
```
Before the change:
```
$ './client/node_modules/.bin/eslint' '--format=json' '--no-color' '--config' './client/.eslintrc' '--fix ' '/Users/mmark/code/my-repo/client/src/index.js'
Oops! Something went wrong! :(
ESLint: 6.8.0.
ESLint couldn't find the plugin "eslint-plugin-react".
(The package "eslint-plugin-react" was not found when loaded as a Node module from the directory "/Users/mmark/code/my-repo".)
```
After the change:
```
$ './client/node_modules/.bin/eslint' '--format=json' '--no-color' '--config' './client/.eslintrc' '--fix ' '/Users/mmark/code/metro/client/src/index.js' '--resolve-plugins-relative-to' './client'
[successful …
```
=> Pass working directory so ESLint can find plugins

src/ESLintLinter.php
Pasted from https://github.com/pinterest/arcanist-linters/issues/80
When there are autofixable lint errors detected by eslint, the order of operations is:
1) `arc diff`
2) if there are uncommited changes, amend or commit
3) arc lint, which autofixes and returns **successful**
4) autofixed changes are **not** committed nor staged
5) diff is pushed to phabricator **without** changes
This means that `arc diff` fails to properly apply lint changes before creating a diff.
See messages for a file provided by eslint@6.8.0
```
"messages": [
{
"ruleId": "prettier/prettier",
"severity": 2,
"message": "Replace `(flow.component·&&·flow.component.archived)` with `flow.component·&&·flow.component.archived`",
"line": 61,
"column": 10,
"nodeType": null,
"messageId": "replace",
"endLine": 61,
"endColumn": …
```
=> Support autofix with eslint

src/ESLintLinter.php
1) Update substrings to be resolved using `mb_substr` instead of `substr` in case the input text is unicode.
2) Add `isset` check before resolving `'fix'` index in the offense. This is throwing an error on every linter without a fix.
Tested by making local changes with unicode strings and verifying the fix was applied as expected:
#Before fix
```
[2021-06-23 05:56:35] ERROR 8: Undefined index: fix at [[repo]/.pinterest-linters/src/ESLintLinter.php:168]
arcanist(), phutil(), pinterest-linters(head=[branch], ref.master=029aa63c3ef7, ref.[branch]=9c6778333e2a)
#0 ESLintLinter::parseLinterOutput(string, integer, string, string) called at [<arcanist>/src/lint/linter/ArcanistExternalLinter.php:437]
#1 ArcanistExternalLinter::resolveFuture(string, ExecFuture) called at …
```
=> Add multibyte (unicode) safety and key check fix

src/ThriftCheckLinter.php
More recent versions of thriftcheck use a more compliant GCC-style
output format which includes a space before the "severity" group.
This matches similar tools, like shellcheck.
https://github.com/pinterest/thriftcheck/pull/32
This change adjusts the handler's pattern to parse this format in a
backwards-compatible way (even though backwards compatibility isn't
critical long-term as thriftcheck itself is close to its 1.0 release).
=> Revise the thriftcheck error pattern

README.md, src/GraphQLSchemaLinter.php
This extra verification is achieved by adding the excerpt below to .arclint:
```
"graphql-schema.dependencies": {
"@pinterest/graphql-lint-rules": "1.0.0"
},
```
=> Add dependency verification on GraphQLSchemaLinter

src/GraphQLSchemaLinter.php
In bash, `cd` will print the directory to stdout, so we also redirect
that output to /dev/null.
=> Also ignore `cd` output from stdout

src/GraphQLSchemaLinter.php
We were previously using the binary path to determine the location
of installed packages (dependencies), but that's unreliable because
it can vary based on installation method, the $PATH, etc.
Instead, we trust our configured `cwd` to determine the package
installation root.
=> Look for packages below the `cwd` path

src/Flake8Linter.php
`flake8` uses the `argparse` library, which by default [wraps output to a max character limit](https://docs.python.org/dev/library/argparse.html#formatter-class).
When running `flake8 --version` in an environment with several `flake8` plugins, the resulting output can easily be split over multiple lines, e.g.
```
4.0.1 (assertive: 2.1.0, dlint: 0.12.0, mccabe: 0.6.1, naming: 0.11.1,
pinboard-author: 1.0.0, pinboard-except-comma: 1.0.0, pinboard-exception-
message: 1.0.0, pinboard-imports: 1.0.0, pinboard-log-lint-errors: 1.0.0,
pinboard-lru-cache: 1.0.0, pinboard-mutable-args: 1.0.0, pinboard-python3:
1.1.0, pinboard-super-call: 1.0.0, pinboard-testcase: 1.0.0, pinboard-tuples:
1.0.0, pinboard-unittests: 1.0.0, pycodestyle: 2.8.0, pyflakes: 2.4.0) CPython
3.7.13 on Darwin
```
Our regex …
=> Handle text-wrapped output from `flake8 --version`

src/Flake8Linter.php, src/GraphQLSchemaLinter.php, src/PinterestExternalLinter.php
A couple of our linters, `Flake8` and `GraphQLSchema`, have additional version checks for the linter's dependencies. These are currently executed when checking the version of the linter binary.
This commit defers checking of these additional dependencies until the time where the linter is to actually be run, via a new `checkAdditionalVersions()` method.
In a larger codebase, it may be common to have many linters configured that only operate on a subset of it (different languages, subdirectories in a monorepo, etc). `arcanist` currently accounts for this in part by allowing a linter not to be installed, and only complaining about that if it finds paths that require that linter. In a similar manner, this commit takes the approach that if a developer has a linter installed for one part of …
=> Check additional linter dependencies only if run
